### ISSUE TITLE
Implement system test for unloading a database with modified schema

### ISSUE THREAD

**Issue by miyconst** [Starcounter/StarDump#87]
There should be a test which would unload a database with modified schema. The database should meet the following criterias:

- Contain a dropped table with `DROP TABLE X`. The table should have records.
- Contain a dropped column with `ALTER TABLE X DROP COLUMN x`. The table should have records inserted before and after the column drop.
- Contain a modified table. The table should be created with N columns, and later updated to N + 1 columns. The table should have records inserted before and after the modification.

@k-rus, @linkdata, @alexanderstc can you add some other cases to test?

**Comment by linkdata** [comment]
* Type change test. Column `A` having type `X` is removed, and re-added with type `Y`.
* Type swap test. Column `A` with type `X` and column `B` with type `Y` are removed, and re-added with the types swapped.

**Comment by ubbeK** [comment]
Comment from @miyconst 
> - Create a database.
> - Start a `Program.cs` with a database classes and some insertions in the `Main` function.
> - Stop the app.
> - Start an empty `Program.cs` and perform DDL statements like `DROP TABLE` and `DROP COLUMN`.
> - Start a `Program.cs` with modified database classes.
> - Unload the database.
> - Check the unload result. (edited)

This should all be possible to do in https://github.com/Starcounter/StarDump/tree/master/test/StarDump.System.Tests (which is executed through https://github.com/Starcounter/StarDump/blob/master/scripts/stardump_system_test.py). Then you don't have to bother with the TC part but you still need to use `star.exe` processes to run the Apps. This is not something for `Starcounter.Xunit.Runner` since all the 3 different `Program.cs` executions would be 3 different Xunit execution suites.

**Comment by miyconst** [comment]
Closing as done.
